export const ADMIN_USERS_REQUEST = "ADMIN_USERS_REQUEST";
export const ADMIN_USERS_SUCCESS = "ADMIN_USERS_SUCCESS";
export const ADMIN_USERS_FAIL = "ADMIN_USERS_FAIL";

// ================= DELETE USER =================

export const ADMIN_DELETE_USER_REQUEST = "ADMIN_DELETE_USER_REQUEST";

export const ADMIN_DELETE_USER_SUCCESS = "ADMIN_DELETE_USER_SUCCESS";

export const ADMIN_DELETE_USER_FAIL = "ADMIN_DELETE_USER_FAIL";

// ================= UPDATE ROLE =================

export const ADMIN_UPDATE_ROLE_REQUEST = "ADMIN_UPDATE_ROLE_REQUEST";

export const ADMIN_UPDATE_ROLE_SUCCESS = "ADMIN_UPDATE_ROLE_SUCCESS";

export const ADMIN_UPDATE_ROLE_FAIL = "ADMIN_UPDATE_ROLE_FAIL";

// ================= ADMIN STATS =================

export const ADMIN_STATS_REQUEST = "ADMIN_STATS_REQUEST";

export const ADMIN_STATS_SUCCESS = "ADMIN_STATS_SUCCESS";

export const ADMIN_STATS_FAIL = "ADMIN_STATS_FAIL";

// ================= ADMIN ANALYTICS =================

export const ADMIN_ANALYTICS_REQUEST = "ADMIN_ANALYTICS_REQUEST";

export const ADMIN_ANALYTICS_SUCCESS = "ADMIN_ANALYTICS_SUCCESS";

export const ADMIN_ANALYTICS_FAIL = "ADMIN_ANALYTICS_FAIL";
