export const COURSE_LIST_REQUEST = "COURSE_LIST_REQUEST";

export const COURSE_LIST_SUCCESS = "COURSE_LIST_SUCCESS";

export const COURSE_LIST_FAIL = "COURSE_LIST_FAIL";

export const COURSE_DETAILS_REQUEST = "COURSE_DETAILS_REQUEST";

export const COURSE_DETAILS_SUCCESS = "COURSE_DETAILS_SUCCESS";

export const COURSE_DETAILS_FAIL = "COURSE_DETAILS_FAIL";

export const MY_COURSES_REQUEST = "MY_COURSES_REQUEST";

export const MY_COURSES_SUCCESS = "MY_COURSES_SUCCESS";

export const MY_COURSES_FAIL = "MY_COURSES_FAIL";

// ================= TEACHER COURSES =================

export const TEACHER_COURSES_REQUEST = "TEACHER_COURSES_REQUEST";

export const TEACHER_COURSES_SUCCESS = "TEACHER_COURSES_SUCCESS";

export const TEACHER_COURSES_FAIL = "TEACHER_COURSES_FAIL";

// ================= CREATE COURSE =================

export const CREATE_COURSE_REQUEST = "CREATE_COURSE_REQUEST";

export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";

export const CREATE_COURSE_FAIL = "CREATE_COURSE_FAIL";

// ================= DELETE COURSE =================

export const DELETE_COURSE_REQUEST = "DELETE_COURSE_REQUEST";

export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";

export const DELETE_COURSE_FAIL = "DELETE_COURSE_FAIL";
