export const FOREX_NEWS_LIST_REQUEST = "FOREX_NEWS_LIST_REQUEST";
export const FOREX_NEWS_LIST_SUCCESS = "FOREX_NEWS_LIST_SUCCESS";
export const FOREX_NEWS_LIST_FAIL = "FOREX_NEWS_LIST_FAIL";

export const FOREX_NEWS_DETAILS_REQUEST = "FOREX_NEWS_DETAILS_REQUEST";
export const FOREX_NEWS_DETAILS_SUCCESS = "FOREX_NEWS_DETAILS_SUCCESS";
export const FOREX_NEWS_DETAILS_FAIL = "FOREX_NEWS_DETAILS_FAIL";

