export const LEAD_LIST_REQUEST = "LEAD_LIST_REQUEST";
export const LEAD_LIST_SUCCESS = "LEAD_LIST_SUCCESS";
export const LEAD_LIST_FAIL = "LEAD_LIST_FAIL";

export const LEAD_DETAILS_REQUEST = "LEAD_DETAILS_REQUEST";
export const LEAD_DETAILS_SUCCESS = "LEAD_DETAILS_SUCCESS";
export const LEAD_DETAILS_FAIL = "LEAD_DETAILS_FAIL";

export const LEAD_UPDATE_REQUEST = "LEAD_UPDATE_REQUEST";
export const LEAD_UPDATE_SUCCESS = "LEAD_UPDATE_SUCCESS";
export const LEAD_UPDATE_FAIL = "LEAD_UPDATE_FAIL";
export const LEAD_UPDATE_RESET = "LEAD_UPDATE_RESET";

export const LEAD_DELETE_REQUEST = "LEAD_DELETE_REQUEST";
export const LEAD_DELETE_SUCCESS = "LEAD_DELETE_SUCCESS";
export const LEAD_DELETE_FAIL = "LEAD_DELETE_FAIL";
