// ================= GET ALL LIVE COURSES =================

export const LIVE_COURSE_LIST_REQUEST = "LIVE_COURSE_LIST_REQUEST";

export const LIVE_COURSE_LIST_SUCCESS = "LIVE_COURSE_LIST_SUCCESS";

export const LIVE_COURSE_LIST_FAIL = "LIVE_COURSE_LIST_FAIL";

// ================= CREATE LIVE COURSE =================

export const LIVE_COURSE_CREATE_REQUEST = "LIVE_COURSE_CREATE_REQUEST";

export const LIVE_COURSE_CREATE_SUCCESS = "LIVE_COURSE_CREATE_SUCCESS";

export const LIVE_COURSE_CREATE_FAIL = "LIVE_COURSE_CREATE_FAIL";

// ================= MY LIVE COURSES =================

export const MY_LIVE_COURSES_REQUEST = "MY_LIVE_COURSES_REQUEST";

export const MY_LIVE_COURSES_SUCCESS = "MY_LIVE_COURSES_SUCCESS";

export const MY_LIVE_COURSES_FAIL = "MY_LIVE_COURSES_FAIL";

// ================= TEACHER LIVE COURSES =================

export const TEACHER_LIVE_COURSES_REQUEST = "TEACHER_LIVE_COURSES_REQUEST";

export const TEACHER_LIVE_COURSES_SUCCESS = "TEACHER_LIVE_COURSES_SUCCESS";

export const TEACHER_LIVE_COURSES_FAIL = "TEACHER_LIVE_COURSES_FAIL";

// ================= ENROLL LIVE COURSE =================

export const LIVE_COURSE_ENROLL_REQUEST = "LIVE_COURSE_ENROLL_REQUEST";

export const LIVE_COURSE_ENROLL_SUCCESS = "LIVE_COURSE_ENROLL_SUCCESS";

export const LIVE_COURSE_ENROLL_FAIL = "LIVE_COURSE_ENROLL_FAIL";

// ================= DELETE LIVE COURSE =================

export const LIVE_COURSE_DELETE_REQUEST = "LIVE_COURSE_DELETE_REQUEST";

export const LIVE_COURSE_DELETE_SUCCESS = "LIVE_COURSE_DELETE_SUCCESS";

export const LIVE_COURSE_DELETE_FAIL = "LIVE_COURSE_DELETE_FAIL";
