export const ANALYSIS_LIST_REQUEST = "ANALYSIS_LIST_REQUEST";
export const ANALYSIS_LIST_SUCCESS = "ANALYSIS_LIST_SUCCESS";
export const ANALYSIS_LIST_FAIL = "ANALYSIS_LIST_FAIL";

export const ANALYSIS_DETAILS_REQUEST = "ANALYSIS_DETAILS_REQUEST";
export const ANALYSIS_DETAILS_SUCCESS = "ANALYSIS_DETAILS_SUCCESS";
export const ANALYSIS_DETAILS_FAIL = "ANALYSIS_DETAILS_FAIL";

export const ANALYSIS_CREATE_REQUEST = "ANALYSIS_CREATE_REQUEST";
export const ANALYSIS_CREATE_SUCCESS = "ANALYSIS_CREATE_SUCCESS";
export const ANALYSIS_CREATE_FAIL = "ANALYSIS_CREATE_FAIL";
export const ANALYSIS_CREATE_RESET = "ANALYSIS_CREATE_RESET";

export const ANALYSIS_DELETE_REQUEST = "ANALYSIS_DELETE_REQUEST";
export const ANALYSIS_DELETE_SUCCESS = "ANALYSIS_DELETE_SUCCESS";
export const ANALYSIS_DELETE_FAIL = "ANALYSIS_DELETE_FAIL";

export const ANALYSIS_UPDATE_REQUEST = "ANALYSIS_UPDATE_REQUEST";
export const ANALYSIS_UPDATE_SUCCESS = "ANALYSIS_UPDATE_SUCCESS";
export const ANALYSIS_UPDATE_FAIL = "ANALYSIS_UPDATE_FAIL";
