export const SUPPORT_CREATE_REQUEST = "SUPPORT_CREATE_REQUEST";
export const SUPPORT_CREATE_SUCCESS = "SUPPORT_CREATE_SUCCESS";
export const SUPPORT_CREATE_FAIL = "SUPPORT_CREATE_FAIL";
export const SUPPORT_CREATE_RESET = "SUPPORT_CREATE_RESET";
