export const WEBINAR_LIST_REQUEST = "WEBINAR_LIST_REQUEST";
export const WEBINAR_LIST_SUCCESS = "WEBINAR_LIST_SUCCESS";
export const WEBINAR_LIST_FAIL = "WEBINAR_LIST_FAIL";

export const WEBINAR_CREATE_REQUEST = "WEBINAR_CREATE_REQUEST";
export const WEBINAR_CREATE_SUCCESS = "WEBINAR_CREATE_SUCCESS";
export const WEBINAR_CREATE_FAIL = "WEBINAR_CREATE_FAIL";
export const WEBINAR_CREATE_RESET = "WEBINAR_CREATE_RESET";

export const WEBINAR_DELETE_REQUEST = "WEBINAR_DELETE_REQUEST";
export const WEBINAR_DELETE_SUCCESS = "WEBINAR_DELETE_SUCCESS";
export const WEBINAR_DELETE_FAIL = "WEBINAR_DELETE_FAIL";
